### ISSUE TITLE
Integration with Rocket.Chat broken

### ISSUE THREAD

**Issue by cjhille** [alangecker/bigbluebutton-docker#21]
I've tried bundling the dockerized BBB version with a recent rocket.chat server (and their default integration for BBB). Unfortunately when clicking the "Start Meeting" button, nothing happens. For a lack of a bare metal BBB installation, I can't 100% confirm, that the issues related to the docker setup, but I haven't found a bug report for the default BBB / Rocket.Chat integration.

The Rocket.Chat HTML client shows this error message:

```
"Error: Internal server error [500]
    at M._livedata_result (https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:154:17753)
    at M.onMessage (https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:154:20094)
    at https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:152:2680
    at Array.forEach (<anonymous>)
    at u.forEachCallback (https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:152:3747)
    at k.socket.onmessage (https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:152:2650)
    at k.r.dispatchEvent (https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:152:6254)
    at k._dispatchMessage (https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:152:19887)
    at k._didMessage (https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:152:20789)
    at WebSocket.o.ws.onmessage (https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:152:22942)"
```

Rocket.Chat Server Log states:

```
Exception while invoking method 'bbbJoin' Error: failed [404] <Map><timestamp>1593446906299</timestamp><status>404</status><error>Not Found</error><message>No message available</message><path>/bigbluebutton/api/hooks/create</path></Map>
    at Object.exports.makeErrorByStatus (packages/http.js:176:10)
    at Request._callback (packages/http.js:140:24)
    at Request.self.callback (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at IncomingMessage.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

The BBB nginx log states:

```
2020/06/29 16:08:26 [error] 7#7: *1303 open() "/etc/nginx/html/client/conf/config.xml" failed (2: No such file or directory), client: 172.31.0.2, server: _, request: "GET /client/conf/config.xml HTTP/1.1", host: "konferenz.REDACTED.de"
```

Since the nginx error log displays the same message as in #20 , I assume it might be related.

**Comment by workdojos** [comment]
> 
> 
> I've tried bundling the dockerized BBB version with a recent rocket.chat server (and their default integration for BBB). Unfortunately when clicking the "Start Meeting" button, nothing happens. For a lack of a bare metal BBB installation, I can't 100% confirm, that the issues related to the docker setup, but I haven't found a bug report for the default BBB / Rocket.Chat integration.
> 
> The Rocket.Chat HTML client shows this error message:
> 
> ```
> "Error: Internal server error [500]
>     at M._livedata_result (https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:154:17753)
>     at M.onMessage (https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:154:20094)
>     at https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:152:2680
>     at Array.forEach (<anonymous>)
>     at u.forEachCallback (https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:152:3747)
>     at k.socket.onmessage (https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:152:2650)
>     at k.r.dispatchEvent (https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:152:6254)
>     at k._dispatchMessage (https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:152:19887)
>     at k._didMessage (https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:152:20789)
>     at WebSocket.o.ws.onmessage (https://chat.REDACTED.de/8ca65148339a2675449b4d7a6e2aecf29497c32b.js?meteor_js_resource=true:152:22942)"
> ```
> 
> Rocket.Chat Server Log states:
> 
> ```
> Exception while invoking method 'bbbJoin' Error: failed [404] <Map><timestamp>1593446906299</timestamp><status>404</status><error>Not Found</error><message>No message available</message><path>/bigbluebutton/api/hooks/create</path></Map>
>     at Object.exports.makeErrorByStatus (packages/http.js:176:10)
>     at Request._callback (packages/http.js:140:24)
>     at Request.self.callback (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)
>     at Request.emit (events.js:311:20)
>     at Request.EventEmitter.emit (domain.js:482:12)
>     at Request.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)
>     at Request.emit (events.js:311:20)
>     at Request.EventEmitter.emit (domain.js:482:12)
>     at IncomingMessage.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)
>     at Object.onceWrapper (events.js:417:28)
>     at IncomingMessage.emit (events.js:323:22)
>     at IncomingMessage.EventEmitter.emit (domain.js:482:12)
>     at endReadableNT (_stream_readable.js:1204:12)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> ```
> 
> The BBB nginx log states:
> 
> ```
> 2020/06/29 16:08:26 [error] 7#7: *1303 open() "/etc/nginx/html/client/conf/config.xml" failed (2: No such file or directory), client: 172.31.0.2, server: _, request: "GET /client/conf/config.xml HTTP/1.1", host: "konferenz.REDACTED.de"
> ```
> 
> Since the nginx error log displays the same message as in #20 , I assume it might be related.

Hi, I have the same problem, how did you fix it?  Thanks

**Comment by cjhille** [comment]
#23 fixed it for me. Make sure to enable webhooks in .env via `ENABLE_WEBHOOKS=true`
In rocketchat config include the protocol and strip the path from the URL i.e. `https://bbb.yourdomain.com`

**Comment by workdojos** [comment]
> 
> 
> #23 fixed it for me. Make sure to enable webhooks in .env via `ENABLE_WEBHOOKS=true`
> In rocketchat config include the protocol and strip the path from the URL i.e. `https://bbb.yourdomain.com`

You're THE BEST!  Thanks sooo much.  Been pulling my hair out for days over this, you fixed it, and for that I'm grateful!

**Comment by cjhille** [comment]
Actually @alangecker fixed this, but I'm glad it works for you :)
