### ISSUE TITLE
bbb-web can't start because logs file can't open (permission denied), what's the problem?

### ISSUE THREAD

**Issue by yangshenys** [alangecker/bigbluebutton-docker#53]
I installed the bbb-docker successfully on a ubuntu 16.04 system, and then move the containers to a centos 8.2 system. But this error prevent me from using it, I printed the logs and found that the bbb-web is keeping restart. The useful logs are copied here.
```
core_1        | bbb-web        | 03:28:44,912 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1961945640 - No compression will be used
core_1        | bbb-web        | 03:28:44,914 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1961945640 - Will use the pattern /var/log/bigbluebutton/bbb-web.%d{yyyy-MM-dd}.log for the active file
core_1        | bbb-web        | 03:28:44,926 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/var/log/bigbluebutton/bbb-web.%d{yyyy-MM-dd}.log'.
core_1        | bbb-web        | 03:28:44,926 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
core_1        | bbb-web        | 03:28:44,941 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Thu Aug 20 10:03:09 UTC 2020
core_1        | bbb-web        | 03:28:44,944 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - This appender no longer admits a layout as a sub-component, set an encoder instead.
core_1        | bbb-web        | 03:28:44,944 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
core_1        | bbb-web        | 03:28:44,944 |-WARN in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
core_1        | bbb-web        | 03:28:44,946 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: logs/bbb-web.log
core_1        | bbb-web        | 03:28:44,946 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [logs/bbb-web.log]
core_1        | bbb-web        | 03:28:44,948 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(logs/bbb-web.log,true) call failed. java.io.FileNotFoundException: logs/bbb-web.log (Permission denied)
core_1        | bbb-web        | 	at java.io.FileNotFoundException: logs/bbb-web.log (Permission denied)
core_1        | bbb-web        | 	at 	at java.io.FileOutputStream.open0(Native Method)
core_1        | bbb-web        | 	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
core_1        | bbb-web        | 	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
core_1        | bbb-web        | 	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
core_1        | bbb-web        | 	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:204)
core_1        | bbb-web        | 	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:127)
core_1        | bbb-web        | 	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:100)
core_1        | bbb-web        | 	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
core_1        | bbb-web        | 	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
core_1        | bbb-web        | 	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
core_1        | bbb-web        | 	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
core_1        | bbb-web        | 	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
core_1        | bbb-web        | 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
core_1        | bbb-web        | 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
core_1        | bbb-web        | 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
core_1        | bbb-web        | 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
core_1        | bbb-web        | 	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
core_1        | bbb-web        | 	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
core_1        | bbb-web        | 	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
core_1        | bbb-web        | 	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
core_1        | bbb-web        | 	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
core_1        | bbb-web        | 	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
core_1        | bbb-web        | 	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
core_1        | bbb-web        | 	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
core_1        | bbb-web        | 	at 	at org.slf4j.LoggerFactory$getLogger.call(Unknown Source)
core_1        | bbb-web        | 	at 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
core_1        | bbb-web        | 	at 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
core_1        | bbb-web        | 	at 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
core_1        | bbb-web        | 	at 	at org.bigbluebutton.web.Application.<clinit>(Application.groovy)
core_1        | bbb-web        | 	at 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
core_1        | bbb-web        | 	at 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
core_1        | bbb-web        | 	at 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
core_1        | bbb-web        | 	at 	at java.lang.reflect.Method.invoke(Method.java:498)
core_1        | bbb-web        | 	at 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
core_1        | bbb-web        | 	at 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
core_1        | bbb-web        | 	at 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
core_1        | bbb-web        | 	at 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
```
I entered the core container, but only found this log file /var/log/bigbluebutton/bbb-web.log, and the file was empty, while the same file in ubuntu system's container was full of logs. I imagine that maybe some system settings prevent the file from using by java progress, but i can't figure it out any more , what may be the problem?

**Comment by yangshenys** [comment]
I pulled the images from a local hub and interupt the proccedure (default disk space is full), then i moved the docker storage to a new place to continue the proccedure , this might be the cause. When I removed all the cache and pulled again, the problem was solved ……
